### ISSUE TITLE
remove ndistinct

### ISSUE THREAD

**Issue by dcaseykc** [PHSKC-APDE/rads#118]
What does it even mean?

**Comment by dcaseykc** [comment]
@dcolombara : Is this ok todo? If not, what should ndistinct mean for factors? Is it 1 or the number of levels?

**Comment by dcaseykc** [comment]
#94 suggests it should be the number of levels. I don't think this is current practice.

**Comment by dcolombara** [comment]
I *think* this means that we should not calculate / report ndistinct. 

If you want to keep ndistinct so that it reports the number of levels for factors, that's fine. I'm agnostic about it. I'm having a hard time imagining when that would be useful though.

The question then would be what it should return if the "what" is anything except a factor. NA? 0? or 1?

**Comment by dcaseykc** [comment]
I'm going to just get rid of it.

**Comment by dcaseykc** [comment]
Done with upcoming release of 1.0.0
