### ISSUE TITLE
Ensure user is on VPN

### ISSUE THREAD

**Issue by kai-fukutaki** [PHSKC-APDE/rads#322]
I've run into many people asking me about HHSAW keyring credentials, when the actual issue was them not being on VPN. Before saying the "Your hhsaw keyring is not properly configured..." message, the functions should first check that the user is on VPN.

**Comment by dcolombara** [comment]
Ensuring someone is on VPN from within R is non-trivial and the juice is not worth the squeeze. Daniel addressed issue #324 so that the warning when a connection fails first mentions that the user may not be on VPN. Since the two issues are so highly correlated, I'll consider this one closed as well.
