### ISSUE TITLE
get_chars_data returns two pov200grp variables

### ISSUE THREAD

**Issue by elikern-kc** [PHSKC-APDE/rads#326]
R code to reproduce issue: chars_data <- get_data_chars(year = 2017:2021)

There is a pov200grp.x variable with all lower case values and a pov200grp.y variable with sentence case values (which matches the pov200grp variable in the HHSAW SQL table)

I've looked at the get_chars_data function and cannot identify where this issue might be occurring given there is no code that refers to pov200grp.

Thanks!

Eli

**Comment by dcolombara** [comment]
Hi Eli,

I tried to replicate the issue, but I don't see it. The following code shows that, with the latest rads version, I only get 'pov200grp'.

Can you update and confirm whether you still see the *.x and *.y versions?

Thanks,

Danny

> library(data.table)
data.table 1.14.8 using 10 threads (see ?getDTthreads).  Latest news: r-datatable.com
> library(rads)
> packageVersion('rads')
[1] '1.1.7.7'
> list_dataset_columns('chars')[var.names %like% 'pov']
   var.names analytic_ready
1: pov200grp           TRUE
> test = get_data_chars(year = 2022)
> grep('pov', names(test), value = T)
[1] "pov200grp"


From: Eli Kern ***@***.***>
Sent: Thursday, November 9, 2023 9:11 AM
To: PHSKC-APDE/rads ***@***.***>
Cc: Colombara, Danny ***@***.***>; Assign ***@***.***>
Subject: [PHSKC-APDE/rads] get_chars_data returns two pov200grp variables (Issue #326)

[EXTERNAL Email Notice! ] External communication is important to us. Be cautious of phishing attempts. Do not click or open suspicious links or attachments.

R code to reproduce issue: chars_data <- get_data_chars(year = 2017:2021)

There is a pov200grp.x variable with all lower case values and a pov200grp.y variable with sentence case values (which matches the pov200grp variable in the HHSAW SQL table)

I've looked at the get_chars_data function and cannot identify where this issue might be occurring given there is no code that refers to pov200grp.

Thanks!

Eli

-

**Comment by dcolombara** [comment]
☹☹☹

I’m so sorry Danny – the problem was that my rads was not updated. Apologies! I just updated and now indeed I only see one pov200grp variable. Thanks!

Eli

Eli Kern MPH RN | Epidemiologist (he/him)
Assessment, Policy Development, and Evaluation
Public Health - Seattle and King County<https://kingcounty.gov/depts/health.aspx>
phone: 206.263.8727 | email: ***@***.***<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=mailto%3aeli.kern%40kingcounty.gov>

From: Colombara, Danny ***@***.***>
Sent: Thursday, November 9, 2023 9:19 AM
To: PHSKC-APDE/rads ***@***.***>; PHSKC-APDE/rads ***@***.***>
Cc: Assign ***@***.***>; Kern, Eli ***@***.***>
Subject: RE: [PHSKC-APDE/rads] get_chars_data returns two pov200grp variables (Issue #326)

Hi Eli,

I tried to replicate the issue, but I don’t see it. The following code shows that, with the latest rads version, I only get ‘pov200grp’.

Can you update and confirm whether you still see the *.x and *.y versions?

Thanks,

Danny

> library(data.table)
data.table 1.14.8 using 10 threads (see ?getDTthreads).  Latest news: r-datatable.com
> library(rads)
> packageVersion('rads')
[1] ‘1.1.7.7’
> list_dataset_columns('chars')[var.names %like% 'pov']
   var.names analytic_ready
1: pov200grp           TRUE
> test = get_data_chars(year = 2022)
> grep('pov', names(test), value = T)
[1] "pov200grp"


From: Eli Kern ***@***.******@***.***>>
Sent: Thursday, November 9, 2023 9:11 AM
To: PHSKC-APDE/rads ***@***.******@***.***>>
Cc: Colombara, Danny ***@***.******@***.***>>; Assign ***@***.******@***.***>>
Subject: [PHSKC-APDE/rads] get_chars_data returns two pov200grp variables (Issue #326)

[EXTERNAL Email Notice! ] External communication is important to us. Be cautious of phishing attempts. Do not click or open suspicious links or attachments.

R code to reproduce issue: chars_data <- get_data_chars(year = 2017:2021)

There is a pov200grp.x variable with all lower case values and a pov200grp.y variable with sentence case values (which matches the pov200grp variable in the HHSAW SQL table)

I've looked at the get_chars_data function and cannot identify where this issue might be occurring given there is no code that refers to pov200grp.

Thanks!

Eli

**Comment by dcolombara** [comment]
No worries! Thank you!

From: Kern, Eli ***@***.***>
Sent: Thursday, November 9, 2023 9:27 AM
To: Colombara, Danny ***@***.***>; PHSKC-APDE/rads ***@***.***>; PHSKC-APDE/rads ***@***.***>
Cc: Assign ***@***.***>
Subject: RE: [PHSKC-APDE/rads] get_chars_data returns two pov200grp variables (Issue #326)

☹☹☹

I’m so sorry Danny – the problem was that my rads was not updated. Apologies! I just updated and now indeed I only see one pov200grp variable. Thanks!
Eli

Eli Kern MPH RN | Epidemiologist (he/him)
Assessment, Policy Development, and Evaluation
Public Health - Seattle and King County<https://kingcounty.gov/depts/health.aspx>
phone: 206.263.8727 | email: ***@***.***<https://owa.kingcounty.gov/owa/redir.aspx?C=TNuruUR_x0mMeOqn6rueKCfnLzCcxdAICR3iDfSS8atu12V25XSLIp_1k_j_A9NKOb-a_2dkPVw.&URL=mailto%3aeli.kern%40kingcounty.gov>

From: Colombara, Danny ***@***.******@***.***>>
Sent: Thursday, November 9, 2023 9:19 AM
To: PHSKC-APDE/rads ***@***.******@***.***>>; PHSKC-APDE/rads ***@***.******@***.***>>
Cc: Assign ***@***.******@***.***>>; Kern, Eli ***@***.******@***.***>>
Subject: RE: [PHSKC-APDE/rads] get_chars_data returns two pov200grp variables (Issue #326)

Hi Eli,

I tried to replicate the issue, but I don’t see it. The following code shows that, with the latest rads version, I only get ‘pov200grp’.

Can you update and confirm whether you still see the *.x and *.y versions?

Thanks,

Danny

> library(data.table)
data.table 1.14.8 using 10 threads (see ?getDTthreads).  Latest news: r-datatable.com
> library(rads)
> packageVersion('rads')
[1] ‘1.1.7.7’
> list_dataset_columns('chars')[var.names %like% 'pov']
   var.names analytic_ready
1: pov200grp           TRUE
> test = get_data_chars(year = 2022)
> grep('pov', names(test), value = T)
[1] "pov200grp"


From: Eli Kern ***@***.******@***.***>>
Sent: Thursday, November 9, 2023 9:11 AM
To: PHSKC-APDE/rads ***@***.******@***.***>>
Cc: Colombara, Danny ***@***.******@***.***>>; Assign ***@***.******@***.***>>
Subject: [PHSKC-APDE/rads] get_chars_data returns two pov200grp variables (Issue #326)

[EXTERNAL Email Notice! ] External communication is important to us. Be cautious of phishing attempts. Do not click or open suspicious links or attachments.

R code to reproduce issue: chars_data <- get_data_chars(year = 2017:2021)

There is a pov200grp.x variable with all lower case values and a pov200grp.y variable with sentence case values (which matches the pov200grp variable in the HHSAW SQL table)

I've looked at the get_chars_data function and cannot identify where this issue might be occurring given there is no code that refers to pov200grp.

Thanks!

Eli
